In [1]:
!pip install -q pandas numpy scikit-learn

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
data = {
    "Age":[18,20,22,25,28,30,32,35,40,45,23,27,31,29,26,24,33,38,41,36],
    "Gender":["Male","Female","Male","Female","Male","Female","Male","Female","Male","Female",
              "Male","Female","Male","Female","Male","Female","Male","Female","Male","Female"],
    "Sleep_Hours":[5,8,6,7,4,8,5,7,6,8,5,6,7,8,4,6,7,5,8,6],
    "Stress_Level":["High","Low","Medium","Low","High","Low","High","Medium","Medium","Low",
                    "High","Medium","Low","Low","High","Medium","Low","High","Low","Medium"]
}

df = pd.DataFrame(data)

df.head()

,Age,Gender,Sleep_Hours,Stress_Level
0,18,Male,5,High
1,20,Female,8,Low
2,22,Male,6,Medium
3,25,Female,7,Low
4,28,Male,4,High


In [4]:
encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

target_encoder = LabelEncoder()
df["Stress_Level"] = target_encoder.fit_transform(df["Stress_Level"])

df.head()

,Age,Gender,Sleep_Hours,Stress_Level
0,18,1,5,0
1,20,0,8,1
2,22,1,6,2
3,25,0,7,1
4,28,1,4,0


In [5]:
X = df.drop("Stress_Level", axis=1)
y = df["Stress_Level"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [6]:
model = RandomForestClassifier(random_state=42)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [7]:
y_pred = model.predict(X_test)

In [8]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.75

Classification Report
              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      1.00      1.00         1
           2       0.50      1.00      0.67         1

    accuracy                           0.75         4
   macro avg       0.83      0.83      0.78         4
weighted avg       0.88      0.75      0.75         4


Confusion Matrix
[[1 0 1]
 [0 1 0]
 [0 0 1]]


In [11]:
age = int(input("Enter Age: "))
gender = input("Enter Gender (Male/Female): ")
sleep = float(input("Enter Sleep Hours: "))

if gender.lower() == "male":
    gender = 1
else:
    gender = 0

user = pd.DataFrame([[age, gender, sleep]],
                    columns=["Age","Gender","Sleep_Hours"])

prediction = model.predict(user)[0]

result = target_encoder.inverse_transform([prediction])[0]

print("\nPredicted Stress Level:", result)

if result == "Low":
    print("Suggestion: Keep maintaining a healthy lifestyle and regular exercise.")

elif result == "Medium":
    print("Suggestion: Take breaks, sleep well, and practice relaxation techniques.")

else:
    print("Suggestion: Consider talking to a trusted person or a qualified mental health professional if stress continues.")

Enter Age: 19
Enter Gender (Male/Female): female
Enter Sleep Hours: 8

Predicted Stress Level: Low
Suggestion: Keep maintaining a healthy lifestyle and regular exercise.
